services:
    virgin_channel_guide.regonlised_channel_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ VirginChannelGuideBundle:RegionalisedChannel ]

    virgin_channel_guide.channel_factory:
        class: Virgin\ChannelGuideBundle\Entity\ChannelFactory
        arguments: [@virgin_channel_guide.regonlised_channel_repository]
